### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by lateau** [NotFound/winxed#12]
concat string failed with a string retrieved by get_global in pir.

$ winxed test.winxed
in _test
1.3.1
1 /////////////////////// "winxed version: 1.3.1" is expected

// test.winxed
function main() {
  var global_var = "1.3.1";
  ${ set_global "global_var", global_var };

  _test();
}

function _test() {
  say("in _test");

  var global_var;
  ${ get_global global_var, "global_var" };

  say(global_var);
  say("winxed version: " + global_var); //////////////////////// HERE
}

**Comment by NotFound** [comment]
This is by design. STRING + VAR is the same as var(STRING) + VAR, not as STRING + string(VAR).

If you want concatenation you need a cast to string:
say("winxed version: " + string(global_var));
