### ISSUE TITLE
winxed with pir named parameter

### ISSUE THREAD

**Issue by lateau** [NotFound/winxed#15]
I tried this code in winxed but I got "setup.winxed:202: Unfinished argument list near :".

${ runtests file :flat, command :named('exec') };

Is there any ways call pir sub with named parameters?
winxed version is 1.2.0

**Comment by NotFound** [comment]
The ${  } syntax is not direct inlining pir. the first argument is a pir op name and the others are parsed and evaluated as winxed expressions.

You don't need a pirop to call a function:
    runtests(file:[flat], command:[named('exec')] );
