### ISSUE TITLE
No way to set non-identifier attributes

### ISSUE THREAD

**Issue by Benabik** [NotFound/winxed#23]
I can use the three argument `getattribute` built-in to access attributes with strange names (like `@stages`), but I can't seem to set them.  Only the four argument `setattribute` is available, not the three argument version.

**Comment by NotFound** [comment]
You can use the indirect syntax:

foo._"@stages" = "a";
x = foo._"@stages";

Same as in method calls, it gets optimized to a direct access in this case.

**Comment by Benabik** [comment]
Assuming you mean `foo.*'@stages'`, that does appear to work.
