### ISSUE TITLE
Generated PIR should tell name of .winxed source file

### ISSUE THREAD

**Issue by Whiteknight** [NotFound/winxed#26]
When we compile .winxed to .pir, the generated PIR code has the following header:

  # THIS IS A GENERATED FILE! DO NOT EDIT!
  # Begin generated code

It should also mention the name of the original source file that was used to create the file, if any. This way we can trace back from the generated file to the original source.

See also https://github.com/parrot/parrot/issues/758

**Comment by NotFound** [comment]
This was fixed in 2bd58f9c0914f4a35bfd6832278ea3f0fc8b37aa

**Comment by NotFound** [comment]
Released 1.8.0 with the fix. Closing.
