### ISSUE TITLE
subtraction results in missing opcode

### ISSUE THREAD

**Issue by plobsing** [NotFound/winxed#9]
Code:
function main[main](var argv) {
    var x = 1;
    var y = x - 1;
    say(y);
}

Output:
error:imcc:The opcode 'sub_i_p_ic' (sub<3>) was not found. Check the type and number of the arguments
    in file '(file unknown)' line 15

Expected Output:
0

**Comment by NotFound** [comment]
Fixed in 73cf365c91, thanks.
